"""The task runner. `python tasks.py <task>`.

    core           build the Rust engine core (cargo, release)
    test           every suite
    check          the core, the offline audit, then every suite (what CI runs)
    bench          measure the pipeline end to end and print the numbers
    capabilities   regenerate CAPABILITIES.md from the manifest
    package        build dist/vigil/vigil.exe with PyInstaller
    exetest        run the packaged executable on device:0 for a while and judge the run
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DIST = ROOT / "dist" / "vigil"

# A Windows console is cp1252 by default; a task runner that crashes on a
# character in its own output is the v1 lesson repeated (UX-15).
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(errors="replace")


def _run(argv: list[str], *, cwd: Path | None = None, **kwargs) -> int:
    print(">>", " ".join(argv), flush=True)
    return subprocess.call(argv, cwd=str(cwd or ROOT), **kwargs)


def core() -> int:
    """Build the Rust engine core.

    Not required to run the tests — the kernel has NumPy paths for everything
    but the ground rasteriser, and `tests/test_native.py` skips itself when
    the library is absent. It *is* required for `vigil map`, and it is what
    makes association and rasterisation fast enough to matter.
    """
    if shutil.which("cargo") is None:
        # No URL, deliberately: `tools/offline_audit.py` fails the build on any
        # address in the source tree, and it is right to — an address in a
        # help string is one nobody notices becoming an address in a request.
        print("cargo is not installed; install the Rust toolchain to build the engine core. "
              "The product runs without it — more slowly, and without `vigil map` — "
              "and `vigil doctor` says so.")
        return 1
    crate = ROOT / "core"
    if _run(["cargo", "test", "--lib", "--release"], cwd=crate) != 0:
        return 1
    if _run(["cargo", "build", "--release"], cwd=crate) != 0:
        return 1
    sys.path.insert(0, str(ROOT))
    from vigil.kernel import native

    native.forget()
    if not native.available():
        print(f"the core built but will not load: {native.fault()}")
        return 1
    print(f"engine core ready: {native.loaded_from()}, ABI {native.ABI_VERSION}")
    return 0


def test() -> int:
    return _run([sys.executable, "-m", "pytest", "tests", "-q", "-p", "no:cacheprovider"])


def bench() -> int:
    return _run([sys.executable, str(ROOT / "tools" / "benchmark.py")])


def check() -> int:
    # The core first: a suite that runs without it silently skips the
    # cross-validation between the two implementations, which is the test that
    # makes having two of them safe.
    if shutil.which("cargo") is not None and core() != 0:
        return 1
    for step in ((sys.executable, str(ROOT / "tools" / "offline_audit.py")),):
        if _run(list(step)) != 0:
            return 1
    return test()


def capabilities() -> int:
    sys.path.insert(0, str(ROOT))
    from vigil.capabilities import MANIFEST

    lines = ["# Capabilities", "", "*Generated by `python tasks.py capabilities` from `vigil/capabilities.py`. Do not edit.*", "",
             "| Id | Capability | State | Symbols | Tests | Note |", "|---|---|---|---|---|---|"]
    for c in MANIFEST:
        lines.append(f"| {c.id} | {c.title} | `{c.state}` | {', '.join(f'`{s}`' for s in c.symbols) or '—'} | "
                     f"{', '.join(f'`{t}`' for t in c.tests) or '—'} | {c.note} |")
    counts = {}
    for c in MANIFEST:
        counts[c.state] = counts.get(c.state, 0) + 1
    lines += ["", "Counts: " + ", ".join(f"{k} {v}" for k, v in sorted(counts.items()))]
    (ROOT / "CAPABILITIES.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote CAPABILITIES.md ({len(MANIFEST)} rows)")
    return 0


def _commit() -> str | None:
    try:
        out = subprocess.check_output(["git", "rev-parse", "--short", "HEAD"], cwd=str(ROOT), text=True).strip()
        dirty = subprocess.call(["git", "diff", "--quiet"], cwd=str(ROOT)) != 0
        return out + ("+dirty" if dirty else "")
    except Exception:  # noqa: BLE001
        return None


def package() -> int:
    if shutil.which("pyinstaller") is None and _run([sys.executable, "-c", "import PyInstaller"]) != 0:
        print("PyInstaller is not installed: pip install pyinstaller")
        return 1
    if DIST.exists():
        shutil.rmtree(DIST)
    # Taken before the build, because that is the tree PyInstaller is about
    # to read. Anything edited while it runs will differ from this, which is
    # exactly the state `exetest` must refuse.
    sources = source_digests()
    library = _core_library()
    if library is None:
        print("the engine core is not built, so the package will have no `vigil map` and no fast "
              "paths. Build it first with `python tasks.py core`.")
    code = _run([sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean", "--name", "vigil", "--distpath", str(ROOT / "dist"),
                 "--workpath", str(ROOT / "build"), "--specpath", str(ROOT / "build"), "--collect-all", "onnxruntime", "--collect-data", "tzdata",
                 "--hidden-import", "keyring.backends.Windows", "--hidden-import", "keyring.backends.macOS",
                 "--hidden-import", "keyring.backends.SecretService",
                 "--hidden-import", "PySide6.QtWidgets", "--hidden-import", "PySide6.QtGui",
                 "--exclude-module", "PySide6.QtWebEngineCore", "--exclude-module", "PySide6.QtWebEngineWidgets",
                 "--exclude-module", "PySide6.Qt3DCore", "--exclude-module", "PySide6.QtQuick",
                 "--exclude-module", "PySide6.QtQml", "--exclude-module", "PySide6.QtMultimedia",
                 "--exclude-module", "matplotlib", "--exclude-module", "pytest", "--exclude-module", "onnx",
                 "--paths", str(ROOT),
                 *(["--add-binary", f"{library}{os.pathsep}."] if library else []),
                 str(ROOT / "packaging" / "entry.py")])
    if code != 0:
        return code
    (DIST / "build.json").write_text(json.dumps({"commit": _commit(), "sources": sources,
                                                 "built_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())}),
                                     encoding="utf-8")
    models = ROOT / "models"
    if models.is_dir():
        shutil.copytree(models, DIST / "models", dirs_exist_ok=True)
    if library is not None:
        # Beside the executable as well as inside `_internal`: the loader
        # looks in both, and a deployment that unpacks only what it can see
        # should still get the fast paths.
        shutil.copy2(library, DIST / library.name)
    print(f"packaged to {DIST}")
    return 0


def _core_library() -> Path | None:
    """The built engine core, or `None`. Named here rather than in the loader
    because packaging is the only caller that needs a *path* rather than a
    loaded library."""
    names = {"win32": "vigil_core.dll", "darwin": "libvigil_core.dylib"}
    name = names.get(sys.platform, "libvigil_core.so")
    candidate = ROOT / "core" / "target" / "release" / name
    return candidate if candidate.is_file() else None


def source_digests() -> dict[str, str]:
    """A digest for every source file, so a bundle can be compared with the tree."""
    import hashlib

    out = {}
    for folder in ("vigil", "packaging"):
        for path in sorted((ROOT / folder).rglob("*.py")):
            if "__pycache__" in path.parts:
                continue
            out[path.relative_to(ROOT).as_posix()] = hashlib.sha256(path.read_bytes()).hexdigest()
    return out


def stale_sources(exe: Path) -> list[str]:
    """Source files that differ from the ones this bundle was built from.

    Digests, not timestamps. PyInstaller reads each source at its own moment
    during a build, so an edit made while it runs produces a bundle that
    mixes two versions — and the executable, written at the end, still looks
    newer than every source. That happened here: the packaged window
    imported a function the packaged domain module did not have, and a
    timestamp check called the bundle current.

    `exetest` is the only check that runs the packaged product, so it is the
    only one a wrong bundle can fool: an old executable runs perfectly.
    """
    if not exe.is_file():
        return []
    stamp = exe.parent / "build.json"
    try:
        packaged = json.loads(stamp.read_text(encoding="utf-8")).get("sources") or {}
    except (OSError, ValueError):
        packaged = {}
    if not packaged:
        return ["build.json: this bundle records no source digests"]
    current = source_digests()
    differ = set(current) ^ set(packaged)
    differ |= {name for name in set(current) & set(packaged) if current[name] != packaged[name]}
    return sorted(differ)


def exetest() -> int:
    """The camera is the test medium: the packaged binary on device:0, judged by its own output and log."""
    import argparse

    parser = argparse.ArgumentParser(prog="tasks.py exetest")
    parser.add_argument("--seconds", type=float, default=20.0)
    parser.add_argument("--camera", default="device:0")
    parser.add_argument("--no-model", action="store_true")
    parser.add_argument("--record", action="store_true")
    parser.add_argument("--console", action="store_true", help="drive the window, and photograph it before it closes")
    parser.add_argument("--allow-stale", action="store_true", help="test the built executable even if the source is newer")
    args = parser.parse_args(sys.argv[2:])
    exe = DIST / ("vigil.exe" if os.name == "nt" else "vigil")
    if not exe.is_file():
        print(f"no executable at {exe}; run `python tasks.py package` first")
        return 1
    stale = stale_sources(exe)
    if stale and not args.allow_stale:
        # A pass against yesterday's binary is worse than no test: it is
        # evidence for a change the executable does not contain. This has
        # already happened once, quietly, and the run still said PASS.
        print(f"the bundle was built from different sources: {len(stale)} file(s) differ, "
              f"starting with {stale[0]}; run `python tasks.py package` "
              f"(or --allow-stale to test this bundle on purpose)")
        return 1
    workspace = ROOT / "dist" / "exetest" / time.strftime("%Y%m%d-%H%M%S")
    workspace.mkdir(parents=True)
    if args.console:
        # The window is added a camera first, from the same executable, so the
        # console starts on a site that already exists — the way an operator's
        # second launch does.
        add = [str(exe), "--data-dir", str(workspace), "cameras", "add", "laptop", args.camera,
               "--place", "33.8938,35.5018,2.0,180,-15"]
        if args.record:
            add.append("--record")
        print(">>", " ".join(add), flush=True)
        subprocess.run(add, capture_output=True, text=True, timeout=120)
        argv = [str(exe), "--data-dir", str(workspace), "console", "--for", f"{args.seconds:g}", "--start",
                "--screenshots", str(workspace / "shots")]
    else:
        argv = [str(exe), "--data-dir", str(workspace), "run", args.camera, "--for", f"{args.seconds:g}",
                "--place", "33.8938,35.5018,2.0,180,-15"]
    if args.no_model:
        argv.append("--no-model")
    if args.record and not args.console:
        argv.append("--record")
    print(">>", " ".join(argv), flush=True)
    started = time.monotonic()
    proc = subprocess.run(argv, capture_output=True, text=True, timeout=args.seconds + 60)
    elapsed = time.monotonic() - started
    (workspace / "stdout.txt").write_text(proc.stdout, encoding="utf-8")
    (workspace / "stderr.txt").write_text(proc.stderr, encoding="utf-8")
    log = (workspace / "logs" / "vigil.log")
    log_text = log.read_text(encoding="utf-8", errors="replace") if log.is_file() else ""
    problems = []
    if proc.returncode != 0:
        problems.append(f"exit code {proc.returncode}")
    if "Traceback" in proc.stderr or "Traceback" in log_text:
        problems.append("a traceback was logged")
    if elapsed > args.seconds + 30:
        problems.append(f"ran {elapsed:.0f} s for a {args.seconds:g} s request")
    if "frames" not in log_text:
        problems.append("the log never reported frames")
    if args.console:
        shots = sorted((workspace / "shots").glob("*.png")) if (workspace / "shots").is_dir() else []
        if len(shots) < 5:
            problems.append(f"the console produced {len(shots)} screenshot(s), expected 6")
        else:
            print("screenshots: " + ", ".join(s.name for s in shots))
    print(proc.stdout[-2000:])
    verdict = "PASS" if not problems else "FAIL: " + "; ".join(problems)
    print(f"exetest {verdict} in {elapsed:.0f} s; artefacts in {workspace}")
    (workspace / "verdict.txt").write_text(verdict + "\n", encoding="utf-8")
    return 0 if not problems else 1


TASKS = {"core": core, "test": test, "bench": bench, "check": check, "capabilities": capabilities,
         "package": package, "exetest": exetest}

if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1] not in TASKS:
        print(__doc__)
        sys.exit(2)
    sys.exit(TASKS[sys.argv[1]]())
