"""The task runner. `python tasks.py <task>`.

    test           every suite
    check          offline audit, then every suite (what CI runs)
    capabilities   regenerate CAPABILITIES.md from the manifest
    package        build dist/vigil/vigil.exe with PyInstaller
    exetest        run the packaged executable on device:0 for a while and judge the run
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DIST = ROOT / "dist" / "vigil"

# A Windows console is cp1252 by default; a task runner that crashes on a
# character in its own output is the v1 lesson repeated (UX-15).
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(errors="replace")


def _run(argv: list[str], **kwargs) -> int:
    print(">>", " ".join(argv), flush=True)
    return subprocess.call(argv, cwd=str(ROOT), **kwargs)


def test() -> int:
    return _run([sys.executable, "-m", "pytest", "tests", "-q", "-p", "no:cacheprovider"])


def check() -> int:
    for step in ((sys.executable, str(ROOT / "tools" / "offline_audit.py")),):
        if _run(list(step)) != 0:
            return 1
    return test()


def capabilities() -> int:
    sys.path.insert(0, str(ROOT))
    from vigil.capabilities import MANIFEST

    lines = ["# Capabilities", "", "*Generated by `python tasks.py capabilities` from `vigil/capabilities.py`. Do not edit.*", "",
             "| Id | Capability | State | Symbols | Tests | Note |", "|---|---|---|---|---|---|"]
    for c in MANIFEST:
        lines.append(f"| {c.id} | {c.title} | `{c.state}` | {', '.join(f'`{s}`' for s in c.symbols) or '—'} | "
                     f"{', '.join(f'`{t}`' for t in c.tests) or '—'} | {c.note} |")
    counts = {}
    for c in MANIFEST:
        counts[c.state] = counts.get(c.state, 0) + 1
    lines += ["", "Counts: " + ", ".join(f"{k} {v}" for k, v in sorted(counts.items()))]
    (ROOT / "CAPABILITIES.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote CAPABILITIES.md ({len(MANIFEST)} rows)")
    return 0


def _commit() -> str | None:
    try:
        out = subprocess.check_output(["git", "rev-parse", "--short", "HEAD"], cwd=str(ROOT), text=True).strip()
        dirty = subprocess.call(["git", "diff", "--quiet"], cwd=str(ROOT)) != 0
        return out + ("+dirty" if dirty else "")
    except Exception:  # noqa: BLE001
        return None


def package() -> int:
    if shutil.which("pyinstaller") is None and _run([sys.executable, "-c", "import PyInstaller"]) != 0:
        print("PyInstaller is not installed: pip install pyinstaller")
        return 1
    if DIST.exists():
        shutil.rmtree(DIST)
    code = _run([sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean", "--name", "vigil", "--distpath", str(ROOT / "dist"),
                 "--workpath", str(ROOT / "build"), "--specpath", str(ROOT / "build"), "--collect-all", "onnxruntime",
                 "--hidden-import", "keyring.backends.Windows", "--hidden-import", "keyring.backends.macOS",
                 "--hidden-import", "keyring.backends.SecretService", "--paths", str(ROOT),
                 str(ROOT / "packaging" / "entry.py")])
    if code != 0:
        return code
    (DIST / "build.json").write_text(json.dumps({"commit": _commit(), "built_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())}), encoding="utf-8")
    models = ROOT / "models"
    if models.is_dir():
        shutil.copytree(models, DIST / "models", dirs_exist_ok=True)
    print(f"packaged to {DIST}")
    return 0


def exetest() -> int:
    """The camera is the test medium: the packaged binary on device:0, judged by its own output and log."""
    import argparse

    parser = argparse.ArgumentParser(prog="tasks.py exetest")
    parser.add_argument("--seconds", type=float, default=20.0)
    parser.add_argument("--camera", default="device:0")
    parser.add_argument("--no-model", action="store_true")
    parser.add_argument("--record", action="store_true")
    args = parser.parse_args(sys.argv[2:])
    exe = DIST / ("vigil.exe" if os.name == "nt" else "vigil")
    if not exe.is_file():
        print(f"no executable at {exe}; run `python tasks.py package` first")
        return 1
    workspace = ROOT / "dist" / "exetest" / time.strftime("%Y%m%d-%H%M%S")
    workspace.mkdir(parents=True)
    argv = [str(exe), "--data-dir", str(workspace), "run", args.camera, "--for", f"{args.seconds:g}",
            "--place", "33.8938,35.5018,2.0,180,-15"]
    if args.no_model:
        argv.append("--no-model")
    if args.record:
        argv.append("--record")
    print(">>", " ".join(argv), flush=True)
    started = time.monotonic()
    proc = subprocess.run(argv, capture_output=True, text=True, timeout=args.seconds + 60)
    elapsed = time.monotonic() - started
    (workspace / "stdout.txt").write_text(proc.stdout, encoding="utf-8")
    (workspace / "stderr.txt").write_text(proc.stderr, encoding="utf-8")
    log = (workspace / "logs" / "vigil.log")
    log_text = log.read_text(encoding="utf-8", errors="replace") if log.is_file() else ""
    problems = []
    if proc.returncode != 0:
        problems.append(f"exit code {proc.returncode}")
    if "Traceback" in proc.stderr or "Traceback" in log_text:
        problems.append("a traceback was logged")
    if elapsed > args.seconds + 30:
        problems.append(f"ran {elapsed:.0f} s for a {args.seconds:g} s request")
    if "frames" not in log_text:
        problems.append("the log never reported frames")
    print(proc.stdout[-2000:])
    verdict = "PASS" if not problems else "FAIL: " + "; ".join(problems)
    print(f"exetest {verdict} in {elapsed:.0f} s; artefacts in {workspace}")
    (workspace / "verdict.txt").write_text(verdict + "\n", encoding="utf-8")
    return 0 if not problems else 1


TASKS = {"test": test, "check": check, "capabilities": capabilities, "package": package, "exetest": exetest}

if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1] not in TASKS:
        print(__doc__)
        sys.exit(2)
    sys.exit(TASKS[sys.argv[1]]())
